service: aws-node-sqs-worker-project
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  app:
    handler: src/handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  
  lambda1Example:
    name: lambda1example
    description: A async example for worker
    timeout: 20
    memorySize: 128
    handler: dist/lambda1Function/handler.handler
    environment:
      QUEUE_URL: { Ref: TheQueue }
    events:
      - sqs:
          batchSize: 10
          arn:
            Fn::GetAtt: 
              - lambda1ExampleQueue
              - Arn

resources:
  Resources:
    lambda1ExampleQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: lambda1-queue-function

plugins:
  - serverless-plugin-typescript